version: "3.8"

services:
  app:
    build: .
    environment:
      - DATABASE_URL=${NEON_DATABASE_URL}
      - NEON_POOLED_URL=${NEON_POOLED_URL}
      - JWT_SECRET=${JWT_SECRET}
      - TWILIO_SID=${TWILIO_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - REDIS_URL=redis://redis:6379
    ports:
      - "4000:4000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
